### ISSUE TITLE
Pyproject Toml Nits

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/safehttpx#1]
The description and authors field are off

```toml
description = "A Python package for replicating Gradio applications"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
```
